# credit: https://docs.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions

name: Python CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OUT_PATH: test/data/out
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test/requirements.txt
          sudo apt-get install graphviz
      - name: Static checks
        run: python -m flake8 && python -m mypy pipeline_manager # flake8 settings in [ROOT]/tox.ini
      - name: Test with pytest & calculate coverage
        run: coverage run --source=. -m pytest && coverage xml -o $OUT_PATH/coverage/coverage.xml
        if: success() || failure() # run even if the previous step fails
      - name: Generate HTML code coverage report & display report in console
        run: coverage html -d $OUT_PATH/coverage && coverage report
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ${{ env.OUT_PATH }}/coverage/coverage.xml
      - name: Run mutational tests and save html report
        run: |
          mutmut run --paths-to-mutate test
          mutmut html
          mkdir -p $OUT_PATH/mutmut && mv html $OUT_PATH/mutmut
          rm -f *.*XX *.*XX.* **/*.*XX **/*.*XX.* && rm -rf XX **/XX # remove mutated tests artifacts
      - name: Publish tests artifacts
        uses: actions/upload-artifact@v1
        with:
          name: tests output
          path: ${{ env.OUT_PATH }}
        if: success() || failure()
