# credit: https://docs.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions

name: Python CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OUT_PATH: test/data/out
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r src/requirements.txt
          pip3 install -r test/requirements.txt
      - name: Static checks
        run: python3 -m flake8 && python -m mypy src # flake8 settings in [ROOT]/tox.ini
      - name: Tests
        run: coverage run --source=. -m unittest discover && coverage xml -o $OUT_PATH/coverage.xml
        if: success() || failure() # run even if the previous step fails
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: $OUT_PATH/coverage.xml
      - name: Publish tests artifacts
        uses: actions/upload-artifact@v1
        with:
          name: tests output
          path: ${{ env.OUT_PATH }}
        if: success() || failure()
