# credit: https://docs.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions

name: Pyhton CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r src/requirements.txt
          pip3 install -r test/requirements.txt
      - name: Static checks
        run: python3 -m flake8 && python -m mypy src
      - name: Tests
        run: python3 -m unittest discover
        if: success() || failure() # run even if the previous step fails
      - name: Publish tests artifacts
        uses: actions/upload-artifact@v1
        with:
          name: tests output
          path: test/data/out
        if: success() || failure()
